### ISSUE TITLE
drone jsonnet doesn't output a value with false

### ISSUE THREAD

**Issue by donny-dont** [drone/drone-cli#117]
Hit this issue when trying to set `purge` to false in `plugins/docker`. The `purge` flag is BoolT so if its not supplied its `true`. 

```
  docker_build(image, tag):: {
    name: 'build',
    image: 'plugins/docker',
    pull: 'always',
    settings: {
      // Does not output the value into settings
      purge: false,
      // Does output the value into settings
      purge: 'false',
    },
  },
```

**Comment by tboerger** [comment]
This shouldn't be the case anymore, right?

**Comment by tboerger** [comment]
Ok, this is still a valid issue:

### with false

```
{
  kind: 'pipeline',
  name: 'test',
  steps: [
    {
      name: 'build',
      image: 'plugins/docker',
      pull: 'always',
      settings: {
        purge: false,
      },
    }
  ],
}
```

```
# drone jsonnet --stdout
---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: plugins/docker
  settings:

...
```

### with true

```
{
  kind: 'pipeline',
  name: 'test',
  steps: [
    {
      name: 'build',
      image: 'plugins/docker',
      pull: 'always',
      settings: {
        purge: true,
      },
    }
  ],
}
```

```
---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: plugins/docker
  settings:
    purge: true

...
```
