### ISSUE TITLE
Empty secret places ******** between every character

### ISSUE THREAD

**Issue by johncrenshaw** [drone/drone-cli#121]
Using any simple drone.yml, such as:

```
kind: pipeline
name: default

steps:
- name: Hello World
  image: "alpine:3.8"
  commands:
  - echo "Hello World"
```

And a secret.txt file with an empty secret such as:
```
FOO=""
```

The output for the following command is virtually unreadable:
```
drone exec --secret-file="secret.txt" --trusted
```

The problem is the replace rules prepared for writing lines, which adds a rule to replace nothing with ********, resulting in ******** being inserted after every character of output. An empty string check in the newReplacer function at the end of https://github.com/drone/drone-runtime/blob/master/runtime/line.go would presumably fix the problem.
