### ISSUE TITLE
exec cli not support  custom stage definitions?

### ISSUE THREAD

**Issue by chenjpu** [drone/drone-cli#138]
[ custom stage definitions](https://github.com/drone/drone/issues/2680)

**Comment by bradrydzewski** [comment]
The CLI does not currently support custom stage definitions. The challenge is that _anyone_ can create a custom stage definition which complicates support. We have not devised a solution yet, but it may work similar to git custom commands [1]

[1] http://thediscoblog.com/blog/2014/03/29/custom-git-commands-in-3-steps/

**Comment by chenjpu** [comment]
Got it. Thank you.

**Comment by andrewhowdencom** [comment]
Having it pass through like git commands would be cool. Smth like:

```
kind: pipeline
type: ssh
name: default

server:
  host: 123.45.67.8
  user: user
  ssh_key:
    from_secret: MAGIC_SECRET

steps:
- name: hello
  commands:
  - echo world
```

Looking for a binary package like:

```
drone-exec-ssh
```

Supplying it the pipeline JSON to `STDIN` and watching `STDOUT` for build results. 

That allows shipping CLI packages with the runners themselves. 

(At any rate, I'm happy you're thinking about this, it came up for me today ♥)
