### ISSUE TITLE
check for invalid fields

### ISSUE THREAD

**Issue by foosinn** [drone/drone-cli#152]
drone lint checks currently not for invalid fields. 

i.e. if there is a typo in an option, its just ignored. an error message could easy debugging quit a bit.

```yaml

kind: pipeline
name: default

steps:
  - name: typo
  - image: busybox
  - commmands:
    - echo this will never run
```
