### ISSUE TITLE
env is not expanded if it is used as a docker tag

### ISSUE THREAD

**Issue by quantonganh** [drone/drone-cli#164]
```
❯ drone -v
drone version 1.2.0
```

.drone.yml:

```
---
kind: pipeline
name: default

steps:
  - name: echo-env-in-commands
    image: busybox
    commands:
      - echo "without brackets $MY_ENV"
      - echo "with brackets ${MY_ENV}"
      - echo "double dollar signs $${MY_ENV}"

  - name: use-env-as-docker-tag
    image: busybox:${MY_ENV}
    commands:
      - echo "without brackets $MY_ENV"
      - echo "with brackets ${MY_ENV}"
      - echo "double dollar signs $${MY_ENV}"
```

env file:

```
❯ cat env
MY_ENV=latest
```

`drone exec --env-file env`:

1. with brackets: looks like `${MY_ENV}` is expanded to an empty string and we got:

```
2019/12/25 06:20:12 yaml: line 12: mapping values are not allowed in this context
```

2. without brackets (`$MY_ENV`) or double dollar signs (`$${MY_ENV}`):
- it is expanded correctly in `commands` section
- it is not expanded when using as a docker tag

```
❯ drone exec --env-file env
[echo-env-in-commands:0] + echo "without brackets $MY_ENV"
[echo-env-in-commands:1] without brackets latest
[echo-env-in-commands:2] + echo "with brackets "
[echo-env-in-commands:3] with brackets
[echo-env-in-commands:4] + echo "double dollar signs ${MY_ENV}"
[echo-env-in-commands:5] double dollar signs latest
2019/12/25 06:23:21 invalid reference format
```
