### ISSUE TITLE
Ability to exec all matrix axis from CLI

### ISSUE THREAD

**Issue by jhasse** [drone/drone-cli#49]
Currently matrix variables are blank when doing `drone exec`.

The [0.6.0 release notes](http://docs.drone.io/release-0.6.0) could link to this issue btw.

**Comment by bradrydzewski** [comment]
Yes, the release notes accurately describes the issue. You cannot currently execute a full matrix build from the CLI at this time. Note that you can execute a single axis in a matrix locally:

With the following example matrix:

```
pipeline:
  build:
    image: golang
    commands:
      - echo ${FOO}

matrix:
  FOO:
    - bar
    - baz
```

You can execute a single axis by providing the FOO variable at runtime:

```
FOO=bar drone exec
```
