### ISSUE TITLE
Drone CLI fails with Slack plugin

### ISSUE THREAD

**Issue by ogarcia** [drone/drone-cli#56]
With this `.drone.yml` sample file:

```yaml
pipeline:
  notify-slack:
    image: plugins/slack
    channel: tests
    username: drone
    icon_emoji: ":robot_face:"
    secrets: [ slack_webhook ]
```

I run the following command in bash:

```sh
SLACK_WEBHOOK="https://hooks.slack.com/services/ ..." drone exec
```

And gives me this error:

```
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x822140, 0xc82000a060)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200ed418)
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:476 +0x417
panic(0x822140, 0xc82000a060)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
main.message(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8200ee15c, 0x4, 0x0, 0x0, ...)
	/go/src/github.com/drone-plugins/drone-slack/plugin.go:93 +0x40a
main.Plugin.Exec(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8200ee15c, 0x4, 0x0, 0x0, ...)
	/go/src/github.com/drone-plugins/drone-slack/plugin.go:56 +0x7d
main.run(0xc8200def00, 0x0, 0x0)
	/go/src/github.com/drone-plugins/drone-slack/main.go:190 +0x983
reflect.Value.call(0x780780, 0x9708e8, 0x13, 0x8a9398, 0x4, 0xc8200ed378, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x780780, 0x9708e8, 0x13, 0xc8200ed378, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.HandleAction(0x780780, 0x9708e8, 0xc8200def00, 0x0, 0x0)
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:485 +0x2ee
github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli.(*App).Run(0xc820001380, 0xc82000a210, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/drone-plugins/drone-slack/vendor/github.com/urfave/cli/app.go:244 +0xb05
main.main()
	/go/src/github.com/drone-plugins/drone-slack/main.go:146 +0x17eb
2017/07/05 09:57:55 drone_step_0 : exit code 2
```

To rule out that the issue is generated by use secrets, I try with this `.drone.yml`:

```yml
pipeline:
  notify-slack:
    webhook_url: https://hooks.slack.com/services/ ...
    image: plugins/slack
    channel: tests
    username: drone
    icon_emoji: ":robot_face:"
```

But it gives me same result. It fails with above same error.

In Drone server same both `.drone.yml` files works fine.
